### PR TITLE
Make the script retry parts that sometimes timeout on their connection

### PR DESCRIPTION
**Pull request by Mariox222**
While using the script, the connection would sometimes time out or fail on either the `cipher = make_cipher_for_segment(segment)`  line or on the 
```
for chunk in requests.get(segment.absolute_uri, stream=True):
    file.write(cipher.decrypt(chunk))
```
block. This commit will make the script retry these parts if they fail. This has fixed the script for me

### CODE REVIEW

**Comment by deathtracktor** [comment]
@Mariox222 thanks for your contribution.

Adding imperative retry code might not be the best way of repeating failed function calls. The product already uses [Tenacity](https://github.com/jd/tenacity), so you can simply decorate the function in question in the way it's done [here](https://github.com/deathtracktor/audioknigi-club-downloader-app/blob/master/app.py#L33) (you may have to adjust retry parameters though).

**Comment by Mariox222** [comment]
Thanks for replying @deathtracktor 

I've added tenacity decorator so that those 2 functions are retried if they fail.

Here is an example output I got now with the error messages on:

```
Fetching book metadata, please stand by...
Downloading segment 189/894 [02:00] - Connection error in make_cipher, retrying...
Downloading segment 365/894 [05:00] - Connection error in make_cipher, retrying...
Downloading segment 410/894 [06:30] - Connection error in write_chunks, retrying...
Downloading segment 453/894 [08:00] - Connection error in make_cipher, retrying...
Downloading segment 498/894 [09:30] - Connection error in write_chunks, retrying...
Downloading segment 542/894 [11:00] - Connection error in make_cipher, retrying...
Downloading segment 587/894 [12:31] - Connection error in write_chunks, retrying...
Downloading segment 629/894 [14:00] - Connection error in make_cipher, retrying...
Downloading segment 676/894 [15:32] - Connection error in write_chunks, retrying...
Downloading segment 717/894 [17:00] - Connection error in make_cipher, retrying...
Downloading segment 766/894 [18:33] - Connection error in write_chunks, retrying...
Downloading segment 803/894 [20:00] - Connection error in make_cipher, retrying...
Downloading segment 894/894 [22:00]

ffmep output...

Finished, check the /path/to/mp3 directory
```

**Review by deathtracktor — CHANGES_REQUESTED** [review]
This looks a lot better. One last request: you can avoid re-raising of exceptions by using the built-in `after` feature of Tenacity:
```python
@retry(
    <some retry args>
    after=lambda s: click.echo(f'Retrying connection, attempt #{ s.attempt_number }')
)
def make_foo() -> None:
    """
    This may fail.
    """
    print(1 / 0)
```
(I have not tested it, please do 😸 )

**Comment by Mariox222** [comment]
I've implemented using the after argument. I also tested it and it works

**Review by deathtracktor — APPROVED** [review]

**Pull request merged**
